title: Sandra Fong # your name (or website title) here
logo: "/images/Portfolio-photo-round.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Senior research engineer with 6 years of experience in immersive technology relating to AR,VR and 360 applications, pivoted from 3d assets creation to development. Highly motivated to gain skills and  keep learning as I navigate towards growing as a  web developer.
  <br><br>
  <a href="https://www.linkedin.com/in/sandra-fong-903844248">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://artofsandrafong.weebly.com/">View My Art Portfolio</a> 
  <br>

theme: jekyll-theme-minimal
